// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddToken(ctx context.Context, token string) (string, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteToken(ctx context.Context, token string) error
	DeleteUser(ctx context.Context, id int32) error
	FindToken(ctx context.Context, token string) (string, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id int32) (User, error)
	FindUserByUsername(ctx context.Context, username string) (User, error)
	UpdateEmail(ctx context.Context, arg UpdateEmailParams) (UpdateEmailRow, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
