// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: user_query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (
  full_name, username, email, password
) VALUES (
  $1, $2, $3, $4
) RETURNING id, full_name, username, email, created_at
`

type CreateUserParams struct {
	FullName pgtype.Text
	Username string
	Email    string
	Password string
}

type CreateUserRow struct {
	ID        int32
	FullName  pgtype.Text
	Username  string
	Email     string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Username,
		arg.Email,
		arg.Password,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "user" WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, full_name, username, email, password, created_at, updated_at FROM "user" WHERE email = $1 LIMIT 1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, full_name, username, email, password, created_at, updated_at FROM "user" WHERE id = $1 LIMIT 1
`

func (q *Queries) FindUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, full_name, username, email, password, created_at, updated_at FROM "user" WHERE username = $1 LIMIT 1
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmail = `-- name: UpdateEmail :one
UPDATE "user"
SET email = $2
WHERE id = $1
RETURNING id, full_name, username, email, created_at, updated_at
`

type UpdateEmailParams struct {
	ID    int32
	Email string
}

type UpdateEmailRow struct {
	ID        int32
	FullName  pgtype.Text
	Username  string
	Email     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) (UpdateEmailRow, error) {
	row := q.db.QueryRow(ctx, updateEmail, arg.ID, arg.Email)
	var i UpdateEmailRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE "user"
SET password = $2
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID       int32
	Password string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.Password)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE "user"
SET
  full_name = coalesce($1, full_name),
  username = coalesce($2, username)
WHERE id = $3
RETURNING id, full_name, username, email, created_at, updated_at
`

type UpdateUserParams struct {
	FullName pgtype.Text
	Username pgtype.Text
	ID       int32
}

type UpdateUserRow struct {
	ID        int32
	FullName  pgtype.Text
	Username  string
	Email     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.FullName, arg.Username, arg.ID)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
