// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int32
	FullName  pgtype.Text
	Username  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
