-- migrate:up
CREATE TABLE "user" (
  id SERIAL PRIMARY KEY NOT NULL,
  full_name VARCHAR(70),
  username VARCHAR(16) UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- migrate:down
DROP TABLE "user";
